SCALE = 2

SCREEN_WIDTH = 320 * SCALE
SCREEN_HEIGHT = 240 * SCALE
GROUND_HEIGHT = 32 * SCALE
PLAY_HEIGHT = SCREEN_HEIGHT - GROUND_HEIGHT
FPS = 60

TITLE = "Chick Flap"
GAME_VERSION = "chick-flap-pyxel-v2"

CHICK_X = 88 * SCALE
CHICK_SIZE = 48
CHICK_HITBOX_RADIUS = 16
START_Y = 104 * SCALE
GRAVITY = 0.44
FLAP_VELOCITY = -7.1
MAX_FALL_SPEED = 8.4
ROTATION_UP = -28
ROTATION_DOWN = 72

PIPE_WIDTH = 88
PIPE_GAP = 156
PIPE_SPEED = 4.7
PIPE_SPACING = 272
PIPE_SPAWN_OFFSET = 192
PIPE_MIN_CENTER_Y = 132
PIPE_MAX_CENTER_Y = 300
PIPE_CAP_HEIGHT = 24

SKY_SCROLL_SPEED = 0.6
CLOUD_SCROLL_SPEED = 1.3
GROUND_SCROLL_SPEED = 4.7

READY_BOB_AMPLITUDE = 10
READY_BOB_SPEED = 0.11

TEXT_COLOR = 7
ACCENT_COLOR = 10
PIPE_COLOR = 11
PIPE_SHADOW_COLOR = 3
GROUND_COLOR = 4
GROUND_STRIPE_COLOR = 9
SUN_COLOR = 10
SKY_TOP_COLOR = 12
SKY_BOTTOM_COLOR = 13
STAR_COLOR = 7
CHICK_BODY_COLOR = 10
CHICK_SHADOW_COLOR = 9
CHICK_BEAK_COLOR = 8
CHICK_EYE_COLOR = 0
